project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  search: true
  reader-mode: true
  repo-url: "https://github.com/pawan1198/portfolio"
  repo-actions: [edit, issue]
  site-url: "https://pawan1198.github.io/portfolio/data_vizs.html"
  description: "Pawan"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: data_vizs.qmd
        text: "Data Visualizations"
      - href: statistics-with-r.qmd
        text: "Statistics With R"
      - href: blog.qmd
        text: "Blog"
      - href: about.qmd
        text: "About Me"
tools:
      - icon: rss
        href: index.xml
      - icon: github
        menu:
          - text: "Source Code"
            url:  https://github.com/pawan1198/portfolio
          - text: "Suggestions / Feedback"
            url:  https://github.com/pawan1198/portfolio/issues
format:
  html:
    theme: litera
       - superhero
    css: styles.css
    toc: true

editor: visual

